// IMC 2025-26 Finals — rankings data (8 grades × 50 ranks)
// Generated from IMC_2025-26_Website_Data.csv

window.IMC_DATA = {
  3: [
    { rank: 1, recognition: 'Topper', name: 'Vihaan Shah', school: 'Gem Genesis International School, Ahmedabad' },
    { rank: 2, recognition: 'Top 3', name: 'Dheer Rawell', school: 'JBCN international School, Mulund' },
    { rank: 3, recognition: 'Top 3', name: 'Darshana', school: 'B V Bhavan\'s Rajaji Vidyashram' },
    { rank: 4, recognition: 'Top 10', name: 'Aviraj Gupta', school: 'Thakur Public School' },
    { rank: 5, recognition: 'Top 10', name: 'Darsh', school: 'CMS Aliganj Campus I' },
    { rank: 6, recognition: 'Top 10', name: 'Virat Bhardwaj', school: 'Delhi Public School Rohini' },
    { rank: 7, recognition: 'Top 10', name: 'Shivaanya Nagpal', school: 'Delhi Public School Rohini' },
    { rank: 8, recognition: 'Top 10', name: 'Tanya Shree', school: 'podar international school besa nagpur' },
    { rank: 9, recognition: 'Top 10', name: 'Dhrihaan Gupta', school: 'Shiv Nadar School, Chennai' },
    { rank: 10, recognition: 'Top 10', name: 'Mirayah', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 11, recognition: 'Top 25', name: 'Selim Anwar Mahmoud', school: 'Kipling School' },
    { rank: 12, recognition: 'Top 25', name: 'Samik', school: 'Shiv nadar' },
    { rank: 13, recognition: 'Top 25', name: 'Vikramaditya Gupta', school: 'Delhi Public School Rohini' },
    { rank: 14, recognition: 'Top 25', name: 'Adhrit Narula', school: 'Delhi Public School Rohini' },
    { rank: 15, recognition: 'Top 25', name: 'Reyansh Sinha', school: 'Challenger Public School - Pimple Saudagar' },
    { rank: 16, recognition: 'Top 25', name: 'Kirtisha.V', school: 'The Lords\' International School' },
    { rank: 17, recognition: 'Top 25', name: 'Swojas Pritam Kondalwar', school: 'Bhartiya Vidya Bhavan\'s' },
    { rank: 18, recognition: 'Top 25', name: 'Nivasini Dhevi V', school: 'Wellsprings Academy | Best CBSE school in Bengaluru' },
    { rank: 19, recognition: 'Top 25', name: 'Ira Chinmay Baxi', school: 'Deens Academy' },
    { rank: 20, recognition: 'Top 25', name: 'Anika', school: 'Birla Open Minds International School' },
    { rank: 21, recognition: 'Top 25', name: 'Pranika Bansal', school: 'Delhi Public School Rohini' },
    { rank: 22, recognition: 'Top 25', name: 'Sharvin Praneet Mhaskar', school: 'Delhi Public School' },
    { rank: 23, recognition: 'Top 25', name: 'Senthuran. Ka', school: 'The Optimus Public School, Sevagoundanur' },
    { rank: 24, recognition: 'Top 25', name: 'Saanvi Vats', school: 'Delhi Public School Rohini' },
    { rank: 25, recognition: 'Top 25', name: 'Manuja Milind Bhadane', school: 'Challenger Public School - Pimple Saudagar' },
    { rank: 26, recognition: 'Top 50', name: 'Fahima Naaz Quadri', school: 'Sunrise English Private School' },
    { rank: 27, recognition: 'Top 50', name: 'Kiyaan Kota', school: 'Suchitra Academy International School' },
    { rank: 28, recognition: 'Top 50', name: 'Samiran Honrao', school: 'Challenger Public School, Pune MH' },
    { rank: 29, recognition: 'Top 50', name: 'Shivaan', school: 'Bluebells School International' },
    { rank: 30, recognition: 'Top 50', name: 'Mithilan', school: 'SV High Global School' },
    { rank: 31, recognition: 'Top 50', name: 'Ananya Maheshwari', school: 'Delhi Public School Rohini' },
    { rank: 32, recognition: 'Top 50', name: 'Madhuragini. D', school: 'The Optimus Public School, Sevagoundanur' },
    { rank: 33, recognition: 'Top 50', name: 'Miraya Rao', school: 'Delhi Public School Rohini' },
    { rank: 34, recognition: 'Top 50', name: 'Aaradhya Agarwal', school: 'Suchitra Academy International School' },
    { rank: 35, recognition: 'Top 50', name: 'Sanvi Vishal Kashid', school: 'KCT\'s Krishna School Karad' },
    { rank: 36, recognition: 'Top 50', name: 'Kiaan Mehra', school: 'LANCERS INTERNATIONAL SCHOOL' },
    { rank: 37, recognition: 'Top 50', name: 'Samarth Pydah', school: 'First Steps School' },
    { rank: 38, recognition: 'Top 50', name: 'R Naren Karthick', school: 'DMI St. Joseph Global School' },
    { rank: 39, recognition: 'Top 50', name: 'S.R.Nilavan', school: 'Agarwal Vidyalaya And Junior College' },
    { rank: 40, recognition: 'Top 50', name: 'Sharanya', school: 'Nalanda Public School' },
    { rank: 41, recognition: 'Top 50', name: 'R. Shree Varshini', school: 'The Optimus Public School' },
    { rank: 42, recognition: 'Top 50', name: 'Aadvik Gupta', school: 'Children\'s Academy - Ghodbunder Road Campus' },
    { rank: 43, recognition: 'Top 50', name: 'Harrman Singh Chatwal', school: 'Suchitra Academy International School' },
    { rank: 44, recognition: 'Top 50', name: 'Rushabh Koulagi', school: 'Navkis Educational Center, Gokula Campus' },
    { rank: 45, recognition: 'Top 50', name: 'Reyansh Josyula', school: 'Kothari International School, Pune' },
    { rank: 46, recognition: 'Top 50', name: 'Rayansh Wahal', school: 'CMS Aliganj Campus I' },
    { rank: 47, recognition: 'Top 50', name: 'Tanishsqa Manish Bhawalkar', school: 'Podar International School Besa, Nagpur' },
    { rank: 48, recognition: 'Top 50', name: 'Ruhaan', school: 'Bright Riders School' },
    { rank: 49, recognition: 'Top 50', name: 'Abhishree', school: 'Sunbeam School & Hostel Varuna' },
    { rank: 50, recognition: 'Top 50', name: 'Devna Ajay', school: 'Bright Riders School' },
  ],
  4: [
    { rank: 1, recognition: 'Topper', name: 'Yuxi Lin', school: 'Singapore School Manila' },
    { rank: 2, recognition: 'Top 3', name: 'Aaryav Taneja', school: 'Shiv Nadar School, Faridabad' },
    { rank: 3, recognition: 'Top 3', name: 'Yuvan Sobti', school: 'Shiv Nadar School (Faridabad)' },
    { rank: 4, recognition: 'Top 10', name: 'Inika Gupta John', school: 'DPS Vasant Kunj' },
    { rank: 5, recognition: 'Top 10', name: 'Ved Jain', school: 'Freedom International School' },
    { rank: 6, recognition: 'Top 10', name: 'Mahi', school: 'Army Public School' },
    { rank: 7, recognition: 'Top 10', name: 'Pihu Choudhary', school: 'NIST College' },
    { rank: 8, recognition: 'Top 10', name: 'Hemakshi Ravi Keshan', school: 'AMNS INTERNATIONAL SCHOOL' },
    { rank: 9, recognition: 'Top 10', name: 'Aroom', school: 'Vista International School, Hyderabad' },
    { rank: 10, recognition: 'Top 10', name: 'Bohao Shi', school: 'Singapore School Manila' },
    { rank: 11, recognition: 'Top 25', name: 'Ahana', school: 'Birla Open Minds International School' },
    { rank: 12, recognition: 'Top 25', name: 'Durvank Ghate', school: 'Challenger Public School, Pune MH' },
    { rank: 13, recognition: 'Top 25', name: 'Avani Pulivendala', school: 'Bright Riders School' },
    { rank: 14, recognition: 'Top 25', name: 'Hariaksha Vishwanathan', school: 'AMNS International School, Hazira, Surat' },
    { rank: 15, recognition: 'Top 25', name: 'Marcus Koistinen', school: 'EEBA' },
    { rank: 16, recognition: 'Top 25', name: 'Jofhitha', school: 'The PSBB Millennium School' },
    { rank: 17, recognition: 'Top 25', name: 'Gauravi Devadiga', school: 'Thakur Public School' },
    { rank: 18, recognition: 'Top 25', name: 'Atmikha Arun', school: 'Bhavans Pearl Wisdom School Sharjah' },
    { rank: 19, recognition: 'Top 25', name: 'Arshan', school: 'Sparkles International School | Best CBSE school in gulbarga' },
    { rank: 20, recognition: 'Top 25', name: 'Anvi Badhan', school: 'DAV Public School, airoli' },
    { rank: 21, recognition: 'Top 25', name: 'Trisha Yadav', school: 'CMS Aliganj Campus I' },
    { rank: 22, recognition: 'Top 25', name: 'Sayona Awasthi', school: 'Birla Open Minds International School' },
    { rank: 23, recognition: 'Top 25', name: 'Aarav', school: 'Agarwal Vidyalaya And Junior College' },
    { rank: 24, recognition: 'Top 25', name: 'Sophia Yehia Khafagi', school: 'Kipling School' },
    { rank: 25, recognition: 'Top 25', name: 'Enaya Chugh', school: 'Gems Genesis International School' },
    { rank: 26, recognition: 'Top 50', name: 'Aditi Rtavari Suri', school: 'Shiv Nadar School' },
    { rank: 27, recognition: 'Top 50', name: 'Iva Somani', school: 'Thakur Public School' },
    { rank: 28, recognition: 'Top 50', name: 'Sushansh Mahakur', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 29, recognition: 'Top 50', name: 'Majd Kobeissi', school: 'Rafic Hariri High School' },
    { rank: 30, recognition: 'Top 50', name: 'Ronav Shahani', school: 'Amity International School' },
    { rank: 31, recognition: 'Top 50', name: 'Bhavyaansh', school: 'JBCN International school Parel' },
    { rank: 32, recognition: 'Top 50', name: 'Amira Ali', school: 'Bluebells School International' },
    { rank: 33, recognition: 'Top 50', name: 'Agastya', school: 'Shiv Nadar School, Chennai' },
    { rank: 34, recognition: 'Top 50', name: 'Divyansh', school: 'DPS Rohini Junior Wing' },
    { rank: 35, recognition: 'Top 50', name: 'Tejas Kamalakara', school: 'Shiv Nadar School, Chennai' },
    { rank: 36, recognition: 'Top 50', name: 'Rishika', school: 'Birla Open Minds International School' },
    { rank: 37, recognition: 'Top 50', name: 'Amay Minocha', school: 'Delhi Public School Rohini' },
    { rank: 38, recognition: 'Top 50', name: 'Akshita Mishra', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 39, recognition: 'Top 50', name: 'Kiaan Setia', school: 'Bluebells School International' },
    { rank: 40, recognition: 'Top 50', name: 'Vrithik Balakarthik', school: 'Alphabet International School' },
    { rank: 41, recognition: 'Top 50', name: 'Dan Alen Asok', school: 'Bright Riders School' },
    { rank: 42, recognition: 'Top 50', name: 'S Joshitha Shri', school: 'BHARATIYA VIDYA BHAVAN\'S V M PUBLIC SCHOOL, VADODARA' },
    { rank: 43, recognition: 'Top 50', name: 'Shloka Shetty', school: 'Sri Sri Ravishankar Vidya Mandir (SSRVM), Mulund, Mumbai' },
    { rank: 44, recognition: 'Top 50', name: 'Diisshan Sable', school: 'Challenger Public School, Pune MH' },
    { rank: 45, recognition: 'Top 50', name: 'S.Likhit', school: 'Podar International School, Besa ,Nagpur' },
    { rank: 46, recognition: 'Top 50', name: 'Visaalakshi Nachiyappan', school: 'Mentor International School' },
    { rank: 47, recognition: 'Top 50', name: 'Ryan', school: 'Gurugram Global Heights School' },
    { rank: 48, recognition: 'Top 50', name: 'Advika Sharma', school: 'Delhi Public School Rohini' },
    { rank: 49, recognition: 'Top 50', name: 'Haya Shehab', school: 'Kipling School' },
    { rank: 50, recognition: 'Top 50', name: 'Faayid Mubeen', school: 'Bright Riders School' },
  ],
  5: [
    { rank: 1, recognition: 'Topper', name: 'Soumajit Paul', school: 'Mentor International School' },
    { rank: 2, recognition: 'Top 3', name: 'A Keerthi Sri', school: 'Apex Pon Vidyashram Velachery' },
    { rank: 3, recognition: 'Top 3', name: 'Riyansh Santosh Dhait', school: 'Kothari International School, Pune' },
    { rank: 4, recognition: 'Top 10', name: 'Tanisha', school: 'Vista International School' },
    { rank: 5, recognition: 'Top 10', name: 'Bhavishya', school: 'Birla Open Minds International School' },
    { rank: 6, recognition: 'Top 10', name: 'Bhupathiraju Nithya Saanvika', school: 'Birla Open Minds International School' },
    { rank: 7, recognition: 'Top 10', name: 'Shruti . Ashru . Wakode', school: 'Challenger Public School - Pimple Saudagar' },
    { rank: 8, recognition: 'Top 10', name: 'Saanvi Talwar', school: 'Delhi Public School Rohini' },
    { rank: 9, recognition: 'Top 10', name: 'D Siya', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 10, recognition: 'Top 10', name: 'Aarav Goel', school: 'Delhi Public School Rohini' },
    { rank: 11, recognition: 'Top 25', name: 'Yuven Gain', school: 'Inventure Academy' },
    { rank: 12, recognition: 'Top 25', name: 'Vaidik Jindal', school: 'Bright Riders School' },
    { rank: 13, recognition: 'Top 25', name: 'Shaurya Ganesh Prabhu', school: 'Thakur Public School' },
    { rank: 14, recognition: 'Top 25', name: 'Joshua.Thysheril', school: 'Inventure Academy' },
    { rank: 15, recognition: 'Top 25', name: 'Vaikhari Swanand Marulkar', school: 'HPC International School' },
    { rank: 16, recognition: 'Top 25', name: 'Cazmir Singh', school: 'Lancers International School' },
    { rank: 17, recognition: 'Top 25', name: 'Arnav', school: 'Ramjas Public School' },
    { rank: 18, recognition: 'Top 25', name: 'Fiona Dey', school: 'BHARATIYA VIDYA BHAVAN\'S V M PUBLIC SCHOOL, VADODARA' },
    { rank: 19, recognition: 'Top 25', name: 'Azara Singh', school: 'Greenwood High - Sarjapur' },
    { rank: 20, recognition: 'Top 25', name: 'Riyan Jain', school: 'BHARATIYA VIDYA BHAVAN\'S V M PUBLIC SCHOOL, VADODARA' },
    { rank: 21, recognition: 'Top 25', name: 'Ridhaan Aggarwal', school: 'Delhi Public School Rohini' },
    { rank: 22, recognition: 'Top 25', name: 'Avyukt Mahadik', school: 'CP GOENKA INTERNATIONAL SCHOOL' },
    { rank: 23, recognition: 'Top 25', name: 'Joshua Abhishek', school: 'SV High Global School Arumbakkam (Cambridge)' },
    { rank: 24, recognition: 'Top 25', name: 'Kanali', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 25, recognition: 'Top 25', name: 'Mohammad Rayyan', school: 'Bright Riders School' },
    { rank: 26, recognition: 'Top 50', name: 'Ayaan Bongu', school: 'Suchitra Academy International School' },
    { rank: 27, recognition: 'Top 50', name: 'Samritthi Jayaprakash', school: 'Bright Riders School' },
    { rank: 28, recognition: 'Top 50', name: 'Krishey', school: 'Sv high' },
    { rank: 29, recognition: 'Top 50', name: 'Ovi', school: 'Delhi Public School - Nadergul' },
    { rank: 30, recognition: 'Top 50', name: 'Shashank Kamalkanth', school: 'KSN Senior Secondary School (CBSE)' },
    { rank: 31, recognition: 'Top 50', name: 'Harsh Jain', school: 'Agarwal Vidyalaya And Junior College' },
    { rank: 32, recognition: 'Top 50', name: 'Dhruv Raheja', school: 'Nalanda Public School' },
    { rank: 33, recognition: 'Top 50', name: 'Prisha Dadhich', school: 'Birla Open Minds International School' },
    { rank: 34, recognition: 'Top 50', name: 'Sridevaansh Pendyala', school: 'Vista International School' },
    { rank: 35, recognition: 'Top 50', name: 'Viswanathan N V', school: 'Basil Woods Nature School, Bangalore' },
    { rank: 36, recognition: 'Top 50', name: 'Anay Jain', school: 'AMNS International School' },
    { rank: 37, recognition: 'Top 50', name: 'Ishan Sharat Rao', school: 'Bright Riders School' },
    { rank: 38, recognition: 'Top 50', name: 'Vedant Gupta', school: 'Delhi Public School Rohini' },
    { rank: 39, recognition: 'Top 50', name: 'Shubh', school: 'Nalanda Public School' },
    { rank: 40, recognition: 'Top 50', name: 'Gaanav .H', school: 'Navkis Educational Centre, Bangalore' },
    { rank: 41, recognition: 'Top 50', name: 'Ishan Yogesh Deshmane', school: 'Vista International School, Hyderabad' },
    { rank: 42, recognition: 'Top 50', name: 'Devaditya Sharma', school: 'The Kalyani School' },
    { rank: 43, recognition: 'Top 50', name: 'Mayra Saluja', school: 'Pragyan School' },
    { rank: 44, recognition: 'Top 50', name: 'Ayaan Ahamed Athavulla Khan', school: 'Bright Riders School' },
    { rank: 45, recognition: 'Top 50', name: 'Srinethra G', school: 'Apex pon vidyashram' },
    { rank: 46, recognition: 'Top 50', name: 'Saathwik Puttagunta', school: 'Army Public School' },
    { rank: 47, recognition: 'Top 50', name: 'Adv_0', school: 'Inventure Academy' },
    { rank: 48, recognition: 'Top 50', name: 'Chaturya P. K.', school: 'Holy Spirit School & PU College' },
    { rank: 49, recognition: 'Top 50', name: 'Ayaansh Kapoor', school: 'Ramniwas Bajaj English High School' },
    { rank: 50, recognition: 'Top 50', name: 'Parshwa Vipul Sheth', school: 'Shree BAK Swadhyay Bhavan, Mumbai' },
  ],
  6: [
    { rank: 1, recognition: 'Topper', name: 'Mayank Bansal', school: 'GD Goenka Public School' },
    { rank: 2, recognition: 'Top 3', name: 'Sreehari Sijil', school: 'Bhavan\'s Pearl Wisdom School' },
    { rank: 3, recognition: 'Top 3', name: 'Labdhi Manoj Jain', school: 'AMNS International School' },
    { rank: 4, recognition: 'Top 10', name: 'Rachana Tulsidas Naik', school: 'Bharatiya Vidya Bhavan\'s Narayan Bandekar School,Upasnagar , Goa ,403726' },
    { rank: 5, recognition: 'Top 10', name: 'Gohita Vrinda Medandrao', school: 'Birla Open Minds International School' },
    { rank: 6, recognition: 'Top 10', name: 'Sanvi Manish Bhawalkar', school: 'Podar International School Besa, Nagpur' },
    { rank: 7, recognition: 'Top 10', name: 'Anish Ankireddypalle', school: 'Delhi Public School, Nadergul' },
    { rank: 8, recognition: 'Top 10', name: 'Satvik Vatsa', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 9, recognition: 'Top 10', name: 'Liam Reign Y. Chuco', school: 'Singapore School Manila' },
    { rank: 10, recognition: 'Top 10', name: 'Prisha Romil Bavishi', school: 'Savitridevi Hariram Agarwal International School' },
    { rank: 11, recognition: 'Top 25', name: 'Avani Tathe', school: 'Birla Open Minds International School' },
    { rank: 12, recognition: 'Top 25', name: 'Rayansh Mehra', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 13, recognition: 'Top 25', name: 'Ruthvika Vankadhara', school: 'Bright Riders School' },
    { rank: 14, recognition: 'Top 25', name: 'Jason Jebezlin. B', school: 'Christwood School, Ponmar' },
    { rank: 15, recognition: 'Top 25', name: 'Jyothy Pagadala', school: 'Birla Open Minds International School' },
    { rank: 16, recognition: 'Top 25', name: 'Charvi Mathur', school: 'Kanakia International School, Bhayandar (CBSE Board)' },
    { rank: 17, recognition: 'Top 25', name: 'Archit Yadav', school: 'CMS Aliganj Campus I' },
    { rank: 18, recognition: 'Top 25', name: 'Myriam Santina', school: 'Rafic Hariri High School' },
    { rank: 19, recognition: 'Top 25', name: 'Shreyaan Gorain', school: 'Delhi Public School Electronic city' },
    { rank: 20, recognition: 'Top 25', name: 'Manan Bajoria', school: 'The Newtown School' },
    { rank: 21, recognition: 'Top 25', name: 'Muhammad Ibrahim', school: 'Australian International School' },
    { rank: 22, recognition: 'Top 25', name: 'Arya Prasad Rana', school: 'Army Public School' },
    { rank: 23, recognition: 'Top 25', name: 'Sidhansh Sajith', school: 'Thakur Public School' },
    { rank: 24, recognition: 'Top 25', name: 'Soham', school: 'Savitridevi Hariram Agarwal International School' },
    { rank: 25, recognition: 'Top 25', name: 'Advit Tandon', school: 'AISG 46' },
    { rank: 26, recognition: 'Top 50', name: 'Kirti Yazhini', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 27, recognition: 'Top 50', name: 'Tashvi Chaturvedi', school: 'SHRI INDRADEO SINGH INTERNATIONAL SCHOOL' },
    { rank: 28, recognition: 'Top 50', name: 'Abhiram Gelle', school: 'Birla Open Minds International School' },
    { rank: 29, recognition: 'Top 50', name: 'Aaradhya Singh', school: 'Birla Open Minds International School' },
    { rank: 30, recognition: 'Top 50', name: 'Ayana Haider', school: 'La Martiniere Girls\' College' },
    { rank: 31, recognition: 'Top 50', name: 'Akshat Jha', school: 'Pawar public school' },
    { rank: 32, recognition: 'Top 50', name: 'Mihit Puri', school: 'Global City International School' },
    { rank: 33, recognition: 'Top 50', name: 'Kavya', school: 'Birla Open Minds International School' },
    { rank: 34, recognition: 'Top 50', name: 'Bhavya Nijhara', school: 'Delhi Public School Rohini' },
    { rank: 35, recognition: 'Top 50', name: 'Malek Mahmoudi', school: 'Rafic Hariri High School' },
    { rank: 36, recognition: 'Top 50', name: 'Adiish Jain', school: 'SHRI INDRADEO SINGH INTERNATIONAL SCHOOL' },
    { rank: 37, recognition: 'Top 50', name: 'Reyansh Jaiswal', school: 'Birla Open Minds International School' },
    { rank: 38, recognition: 'Top 50', name: 'Navya Nandwana', school: 'Thakur Public School' },
    { rank: 39, recognition: 'Top 50', name: 'Ashwi Pawaskar', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 40, recognition: 'Top 50', name: 'Nishan N Pawar', school: 'Bapuji Higher Primary CBSE English Medium School' },
    { rank: 41, recognition: 'Top 50', name: 'Madhav Khandelwal', school: 'Delhi Public School Rohini' },
    { rank: 42, recognition: 'Top 50', name: 'Atiksh. J', school: 'Delhi Public School, Bangalore East' },
    { rank: 43, recognition: 'Top 50', name: 'Aarohi Singh', school: 'BHARATIYA VIDYA BHAVAN\'S V M PUBLIC SCHOOL, VADODARA' },
    { rank: 44, recognition: 'Top 50', name: 'Shreenidhi Chilukuru', school: 'CP GOENKA INTERNATIONAL SCHOOL' },
    { rank: 45, recognition: 'Top 50', name: 'Saney Shinde', school: 'Thakur Public School (Secondary)' },
    { rank: 46, recognition: 'Top 50', name: 'Janhavi Shukla', school: 'La Martiniere Girls\' College' },
    { rank: 47, recognition: 'Top 50', name: 'Hetaksh', school: 'Shri Ram Centennial School' },
    { rank: 48, recognition: 'Top 50', name: 'Trinay', school: 'Army Public School' },
    { rank: 49, recognition: 'Top 50', name: 'Soha Ahmed', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 50, recognition: 'Top 50', name: 'Kartavya Nahata', school: 'DPS Whitefield Mallasandra' },
  ],
  7: [
    { rank: 1, recognition: 'Topper', name: 'Mrunmayee Puranik', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 2, recognition: 'Top 3', name: 'Vimal Manoj Kumar', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 3, recognition: 'Top 3', name: 'Arsh Roshan', school: 'Bright Riders School' },
    { rank: 4, recognition: 'Top 10', name: 'Arav Choudhary', school: 'Birla Open Minds International School' },
    { rank: 5, recognition: 'Top 10', name: 'Parsa', school: 'HPC International School' },
    { rank: 6, recognition: 'Top 10', name: 'Urvi Santosh More Patil', school: 'Bright Riders School' },
    { rank: 7, recognition: 'Top 10', name: 'Abhigyan Sinha', school: 'Navkis Educational Centre, Bangalore' },
    { rank: 8, recognition: 'Top 10', name: 'Aniket Agarwal', school: 'AMNS International School, Hazira,Surat,India' },
    { rank: 9, recognition: 'Top 10', name: 'Kavimugilan S', school: 'Delhi Public School, Nadergul' },
    { rank: 10, recognition: 'Top 10', name: 'Zhijie Zhang', school: 'Singapore School Manila' },
    { rank: 11, recognition: 'Top 25', name: 'Arnav Mishra', school: 'Delhi Public School Rohini' },
    { rank: 12, recognition: 'Top 25', name: 'Vihan', school: 'Army Public School' },
    { rank: 13, recognition: 'Top 25', name: 'Hari Charan Neralla', school: 'Bright Riders School' },
    { rank: 14, recognition: 'Top 25', name: 'Randa Mohiddeen Mneimne', school: 'Rafic Hariri High School' },
    { rank: 15, recognition: 'Top 25', name: 'Yatharth Sharma', school: 'Delhi Public School Rohini' },
    { rank: 16, recognition: 'Top 25', name: 'Aagneya Prasad', school: 'Sunrise English Private School' },
    { rank: 17, recognition: 'Top 25', name: 'Viraj', school: 'Bright Riders School' },
    { rank: 18, recognition: 'Top 25', name: 'Srihari S', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 19, recognition: 'Top 25', name: 'Akshara Nagraj Nadgouda', school: 'Bright Riders School' },
    { rank: 20, recognition: 'Top 25', name: 'Shivaansh Sinha', school: 'Challenger Public School, Pune MH' },
    { rank: 21, recognition: 'Top 25', name: 'Darsh Vignesh', school: 'KSN Senior Secondary School (CBSE)' },
    { rank: 22, recognition: 'Top 25', name: 'Aakarshika Agarwal', school: 'La Martiniere Girls\' College' },
    { rank: 23, recognition: 'Top 25', name: 'Haardit Bhandari', school: 'The Premia Academy, Hyderabad' },
    { rank: 24, recognition: 'Top 25', name: 'Aadhya Nilesh Piraji', school: 'Mentor International School' },
    { rank: 25, recognition: 'Top 25', name: 'Aanya Choudhury', school: 'Delhi Public School, Nadergul' },
    { rank: 26, recognition: 'Top 50', name: 'Ishaan Balasubramanian', school: 'SV High Global School' },
    { rank: 27, recognition: 'Top 50', name: 'R Ajay', school: 'DMI St. Joseph Global School' },
    { rank: 28, recognition: 'Top 50', name: 'Krisheth Rajendran Saravanan', school: 'Bright Riders School' },
    { rank: 29, recognition: 'Top 50', name: 'Aeon Ziven D. Chong', school: 'Singapore School Manila' },
    { rank: 30, recognition: 'Top 50', name: 'Leonie', school: 'HPC International School' },
    { rank: 31, recognition: 'Top 50', name: 'Atharv Tikoo', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 32, recognition: 'Top 50', name: 'Snehan Thirugnanasambandam', school: 'The Lords\' International School' },
    { rank: 33, recognition: 'Top 50', name: 'Tanha', school: 'Australian International School' },
    { rank: 34, recognition: 'Top 50', name: 'Yukti Kotak', school: 'Nalanda Public School' },
    { rank: 35, recognition: 'Top 50', name: 'Devansh Paul', school: 'DPS' },
    { rank: 36, recognition: 'Top 50', name: 'Aarav Shinde', school: 'Challenger Public School, Pune MH' },
    { rank: 37, recognition: 'Top 50', name: 'Tanish Mandal', school: 'The Newtown School' },
    { rank: 38, recognition: 'Top 50', name: 'Athen George', school: 'Bhavans Pearl Wisdom School Sharjah' },
    { rank: 39, recognition: 'Top 50', name: 'Lavanya Thakur', school: 'Dps Ecity' },
    { rank: 40, recognition: 'Top 50', name: 'Advik Patra', school: 'Mentor International School' },
    { rank: 41, recognition: 'Top 50', name: 'Pavithra Gj', school: 'Velammal Bodhi Campus, Vellore' },
    { rank: 42, recognition: 'Top 50', name: 'Parth Bendre', school: 'Savitridevi Hariram Agarwal International School' },
    { rank: 43, recognition: 'Top 50', name: 'Julie Kadri', school: 'Rafic Hariri High School' },
    { rank: 44, recognition: 'Top 50', name: 'Muhammad Ibrahim Mansoor', school: 'Cambridge International School' },
    { rank: 45, recognition: 'Top 50', name: 'Aaria Gupta', school: 'DPS east bengaluru' },
    { rank: 46, recognition: 'Top 50', name: 'Matus Staron', school: 'Spojená škola, Pankúchova 6, Bratislava' },
    { rank: 47, recognition: 'Top 50', name: 'Rion Cheyne R. Hong', school: 'Singapore School Manila' },
    { rank: 48, recognition: 'Top 50', name: 'Vidharshna E M', school: 'PSGR K SCHOOLS' },
    { rank: 49, recognition: 'Top 50', name: 'Yashwant Reddy Gunnam', school: 'Birla Open Minds International School' },
    { rank: 50, recognition: 'Top 50', name: 'Kautik Gupta', school: 'दिल्ली पब्लिक स्कूल' },
  ],
  8: [
    { rank: 1, recognition: 'Topper', name: 'Banaj Bansal', school: 'Ramniwas Bajaj English High School' },
    { rank: 2, recognition: 'Top 3', name: 'Archita Sawanak', school: 'CMS Aliganj Campus I' },
    { rank: 3, recognition: 'Top 3', name: 'Alisha', school: 'Bluebells School International' },
    { rank: 4, recognition: 'Top 10', name: 'Raniya Mumtaz', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 5, recognition: 'Top 10', name: 'Perla Wissam El Hajj', school: 'Rafic Hariri High School' },
    { rank: 6, recognition: 'Top 10', name: 'Nikhilan Vasanthan', school: 'Global City International School' },
    { rank: 7, recognition: 'Top 10', name: 'Yeshas.H', school: 'Global City International School' },
    { rank: 8, recognition: 'Top 10', name: 'Aya Bassem Akra', school: 'Rafic Hariri High School' },
    { rank: 9, recognition: 'Top 10', name: 'Guhan Pannerkumar', school: 'Delhi Public School, Bangalore East' },
    { rank: 10, recognition: 'Top 10', name: 'Anvika Shetty', school: 'Global City International School' },
    { rank: 11, recognition: 'Top 25', name: 'Lohit', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 12, recognition: 'Top 25', name: 'Shreyasi Sinha', school: 'Navkis Educational Centre, Bangalore' },
    { rank: 13, recognition: 'Top 25', name: 'Mohammad El Hajj Chehade', school: 'Iklim High School' },
    { rank: 14, recognition: 'Top 25', name: 'Caren Habib Abdo', school: 'Rafic Hariri High School' },
    { rank: 15, recognition: 'Top 25', name: 'Vihaan Anand', school: 'Delhi Public School Electronic city' },
    { rank: 16, recognition: 'Top 25', name: 'R. Yuvan Kumar', school: 'Keren Public School கேரன்ஸ் பப்ளிக் பள்ளி' },
    { rank: 17, recognition: 'Top 25', name: 'Vihaan Patkar', school: 'DAV Public School, airoli' },
    { rank: 18, recognition: 'Top 25', name: 'Diptanshu Sunil Saraf', school: 'Bright Riders School' },
    { rank: 19, recognition: 'Top 25', name: 'Avinika Patel', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 20, recognition: 'Top 25', name: 'Hasset Fikreselassie', school: 'Reach International Centre of Education - Agona Campus' },
    { rank: 21, recognition: 'Top 25', name: 'A Deekshitha Priya', school: 'Apex Pon Vidyashram Velachery' },
    { rank: 22, recognition: 'Top 25', name: 'Karim Habib Abdo', school: 'Rafic Hariri High School' },
    { rank: 23, recognition: 'Top 25', name: 'Aarna Bist', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 24, recognition: 'Top 25', name: 'Devansh Ray Chaudhuri', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 25, recognition: 'Top 25', name: 'Dagmawi', school: 'Reach international center of education' },
    { rank: 26, recognition: 'Top 50', name: 'Manya V', school: 'Agarwal Vidyalaya And Junior College' },
    { rank: 27, recognition: 'Top 50', name: 'Maanav Rai', school: 'Army Public School, Noida' },
    { rank: 28, recognition: 'Top 50', name: 'Vaibhav Raj', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 29, recognition: 'Top 50', name: 'Nikhitha', school: 'Bright Riders School' },
    { rank: 30, recognition: 'Top 50', name: 'Haya Wazne', school: 'Wellspring Learning Community' },
    { rank: 31, recognition: 'Top 50', name: 'Siya Patidar', school: 'Bright Riders School' },
    { rank: 32, recognition: 'Top 50', name: 'Mudit', school: 'Bluebells School International' },
    { rank: 33, recognition: 'Top 50', name: 'Nassime Majed Bayram', school: 'Rafic Hariri High School' },
    { rank: 34, recognition: 'Top 50', name: 'Monish Vishal Kajbaje', school: 'Bright Riders School' },
    { rank: 35, recognition: 'Top 50', name: 'Aayush Kar', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 36, recognition: 'Top 50', name: 'Harv Arora', school: 'AM/NS international school' },
    { rank: 37, recognition: 'Top 50', name: 'Girum', school: 'Reach International Centre of Education - Agona Campus' },
    { rank: 38, recognition: 'Top 50', name: 'Harshika. C', school: 'CS Academy, Erode' },
    { rank: 39, recognition: 'Top 50', name: 'Abhigya Singh', school: 'La Martiniere Girls\' College' },
    { rank: 40, recognition: 'Top 50', name: 'Tanishkaa', school: 'SV High Global School' },
    { rank: 41, recognition: 'Top 50', name: 'Aayush', school: 'Birla Open Minds International School' },
    { rank: 42, recognition: 'Top 50', name: 'Daksh Sunilldutt Kumawat', school: 'DAV Public School, airoli' },
    { rank: 43, recognition: 'Top 50', name: 'Ayana Samridhi', school: 'Bluebells School International' },
    { rank: 44, recognition: 'Top 50', name: 'M. Ashaj Zain', school: 'Podar International School, Amravati 2' },
    { rank: 45, recognition: 'Top 50', name: 'Lavanya Prashant Gadodiya', school: 'N.V Chinmaya Vidyalaya Shegaon' },
    { rank: 46, recognition: 'Top 50', name: 'Keshvee Nitin Mandela', school: 'Bharatiya Vidya Bhavan\'s Vallabhram Mehta Public School' },
    { rank: 47, recognition: 'Top 50', name: 'Medhavi Gupta', school: 'AMNS INTERNATIONAL SCHOOL' },
    { rank: 48, recognition: 'Top 50', name: 'Aishwarya Avk', school: 'Birla Open Minds International School' },
    { rank: 49, recognition: 'Top 50', name: 'Mohamad Hassan El Zein', school: 'Rafic Hariri High School' },
    { rank: 50, recognition: 'Top 50', name: 'Yoon Jae Ban', school: 'Singapore School Cebu' },
  ],
  9: [
    { rank: 1, recognition: 'Topper', name: 'Sneh Shah', school: 'Thakur Public School' },
    { rank: 2, recognition: 'Top 3', name: 'Saisaurav Samanta', school: 'The Newtown School' },
    { rank: 3, recognition: 'Top 3', name: 'Soumil Manna', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 4, recognition: 'Top 10', name: 'Pavi Sinha', school: 'Delhi Public School Rohini' },
    { rank: 5, recognition: 'Top 10', name: 'Alwalid Rani Saleh', school: 'Rafic Hariri High School' },
    { rank: 6, recognition: 'Top 10', name: 'Aarav Kumar Singh', school: 'CMS Aliganj Campus I' },
    { rank: 7, recognition: 'Top 10', name: 'Shaivi Sinha', school: 'Thakur Public School' },
    { rank: 8, recognition: 'Top 10', name: 'Saket Salil', school: 'Delhi Public School, Bangalore East' },
    { rank: 9, recognition: 'Top 10', name: 'Yaksh Agarwal', school: 'Suchitra Academy International School' },
    { rank: 10, recognition: 'Top 10', name: 'Koppula Virinchi', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 11, recognition: 'Top 25', name: 'Mayol Wahengbam', school: 'Delhi Public School, Bangalore East' },
    { rank: 12, recognition: 'Top 25', name: 'Anish Anand', school: 'Deens Academy' },
    { rank: 13, recognition: 'Top 25', name: 'Yash Agrahari', school: 'St. Peter’s Convent School sec 88, Greater Faridabad.' },
    { rank: 14, recognition: 'Top 25', name: 'Aarav Siddharth Doshi', school: 'Bharatiya Vidya Bhavan\'s Vallabhram Mehta Public School' },
    { rank: 15, recognition: 'Top 25', name: 'Hunar Periwal', school: 'Kanakia International School, Bhayandar (CBSE Board)' },
    { rank: 16, recognition: 'Top 25', name: 'Kritika Tripathi', school: 'St. Peter’s Convent School sec 88, Greater Faridabad.' },
    { rank: 17, recognition: 'Top 25', name: 'Pothula Karthik Sai', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 18, recognition: 'Top 25', name: 'Aradhya Anant Upadhyay', school: 'Global City International School' },
    { rank: 19, recognition: 'Top 25', name: 'Iniyan S', school: 'Keren public school' },
    { rank: 20, recognition: 'Top 25', name: 'Samarth Vishalkumar Shah', school: 'Bharatiya Vidya Bhavan\'s Vallabhram Mehta Public School' },
    { rank: 21, recognition: 'Top 25', name: 'Samarth Agarwal', school: 'LANCERS INTERNATIONAL SCHOOL' },
    { rank: 22, recognition: 'Top 25', name: 'Obasi Eret Michel Ntui', school: 'American International School of Yaounde' },
    { rank: 23, recognition: 'Top 25', name: 'Muthupandi', school: 'Keren Public School கேரன்ஸ் பப்ளிக் பள்ளி' },
    { rank: 24, recognition: 'Top 25', name: 'Gerald George', school: 'Bright Riders School' },
    { rank: 25, recognition: 'Top 25', name: 'Arpit Sharma', school: 'Delhi Public School Rohini' },
    { rank: 26, recognition: 'Top 50', name: 'Ashby Prajeesh', school: 'Sunrise English Private School' },
    { rank: 27, recognition: 'Top 50', name: 'Ayushman Pattanaik', school: 'Summer Fields School, DLF Gurugram' },
    { rank: 28, recognition: 'Top 50', name: 'Pawani Tandon', school: 'CMS Aliganj Campus I' },
    { rank: 29, recognition: 'Top 50', name: 'Tisya Saraooi', school: 'LANCERS INTERNATIONAL SCHOOL' },
    { rank: 30, recognition: 'Top 50', name: 'Kartik Rathod', school: 'Billimoria High School' },
    { rank: 31, recognition: 'Top 50', name: 'Reyaansh Pore', school: 'Thakur Public School' },
    { rank: 32, recognition: 'Top 50', name: 'Ahmad Serhal', school: 'Rafic Hariri High School' },
    { rank: 33, recognition: 'Top 50', name: 'Hardik Pandit', school: 'LANCERS INTERNATIONAL SCHOOL' },
    { rank: 34, recognition: 'Top 50', name: 'Ankush Manna', school: 'Thakur Public School' },
    { rank: 35, recognition: 'Top 50', name: 'Disha Warrier', school: 'OES International School, Vashi' },
    { rank: 36, recognition: 'Top 50', name: 'Anshika Kumar', school: 'Birla Open Minds International School' },
    { rank: 37, recognition: 'Top 50', name: 'Mohammed Fahid', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 38, recognition: 'Top 50', name: 'Yashraj', school: 'Suchitra Academy International School' },
    { rank: 39, recognition: 'Top 50', name: 'Ali Marwan Kobeisse', school: 'Rafic Hariri High School' },
    { rank: 40, recognition: 'Top 50', name: 'Khaled Saleh Faour', school: 'Rafic Hariri High School' },
    { rank: 41, recognition: 'Top 50', name: 'Diya Agrawal', school: 'Rajashree Vidya Mandir' },
    { rank: 42, recognition: 'Top 50', name: 'Sama Mohamed Akra', school: 'Rafic Hariri High School' },
    { rank: 43, recognition: 'Top 50', name: 'Keshav Sambhu', school: 'DAV Public School, airoli' },
    { rank: 44, recognition: 'Top 50', name: 'Dea Vagal', school: 'Thakur Public School' },
    { rank: 45, recognition: 'Top 50', name: 'Sreemedha Mohanty', school: 'AMNS INTERNATIONAL SCHOOL' },
    { rank: 46, recognition: 'Top 50', name: 'Amir Akoum', school: 'Rafic Hariri High School' },
    { rank: 47, recognition: 'Top 50', name: 'K.Akshara', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 48, recognition: 'Top 50', name: 'Seoyoon Bae', school: 'Lancers International School - IB School in Gurgaon' },
    { rank: 49, recognition: 'Top 50', name: 'Sarah Salam Bin Mehfooz', school: 'K12 Schools' },
    { rank: 50, recognition: 'Top 50', name: 'Manthan', school: 'Thakur Public School' },
  ],
  10: [
    { rank: 1, recognition: 'Topper', name: 'Purvesh Kapse', school: 'Podar international school nagpur besa' },
    { rank: 2, recognition: 'Top 3', name: 'Nicole Jessica Jagan', school: 'The Lords\' International School' },
    { rank: 3, recognition: 'Top 3', name: 'Arnav Verma', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 4, recognition: 'Top 10', name: 'Kaushik R', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 5, recognition: 'Top 10', name: 'Aditi Patra', school: 'Mentor International School' },
    { rank: 6, recognition: 'Top 10', name: 'Anvita Mathur', school: 'Airson School' },
    { rank: 7, recognition: 'Top 10', name: 'Beren Aygür', school: 'Gökkuşağı Koleji' },
    { rank: 8, recognition: 'Top 10', name: 'Shaurya Saraf', school: 'Thakur Public School' },
    { rank: 9, recognition: 'Top 10', name: 'Yug Patel', school: 'Thakur Public School' },
    { rank: 10, recognition: 'Top 10', name: 'Krishna S Kanth', school: 'Ponvidyashram Group of Senior Secondary Schools' },
    { rank: 11, recognition: 'Top 25', name: 'D Tamanna', school: 'Pon Vidyashram Group Of CBSE Schools' },
    { rank: 12, recognition: 'Top 25', name: 'Svara Sonkul', school: 'Bright Riders School' },
    { rank: 13, recognition: 'Top 25', name: 'Ishika Biju', school: 'Bright Riders School' },
    { rank: 14, recognition: 'Top 25', name: 'Ojas A Kalmane', school: 'Navkis Educational Center, Gokula Campus' },
    { rank: 15, recognition: 'Top 25', name: 'Mia Khalid Al Khateeb', school: 'Rafic Hariri High School' },
    { rank: 16, recognition: 'Top 25', name: 'Rithisha Jayaprakash', school: 'Bright Riders School' },
    { rank: 17, recognition: 'Top 25', name: 'Areeba Fatima', school: 'Alhussan Int. School - Girls Section' },
    { rank: 18, recognition: 'Top 25', name: 'Aditi Hingwasiya', school: 'Nalanda Public School' },
    { rank: 19, recognition: 'Top 25', name: 'Abilash Ceyon. S', school: 'Alphabet School' },
    { rank: 20, recognition: 'Top 25', name: 'Anay Somani', school: 'Thakur Public School' },
    { rank: 21, recognition: 'Top 25', name: 'Dia Sobhrajani', school: 'St. Xavier\'s High School- Best CBSE School in Gurgaon' },
    { rank: 22, recognition: 'Top 25', name: 'Baikati Nihaanth Reddy', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 23, recognition: 'Top 25', name: 'Anap@1108', school: 'Bilinguale Grundschule Heidelberg | HPC Schulen' },
    { rank: 24, recognition: 'Top 25', name: 'Sidhi Upadhyay', school: 'DAV Public School' },
    { rank: 25, recognition: 'Top 25', name: 'Kriya Shah', school: 'Sri Sri Ravishankar Vidya Mandir (SSRVM), Mulund, Mumbai' },
    { rank: 26, recognition: 'Top 50', name: 'Sanskar Patel', school: 'AMNS international School' },
    { rank: 27, recognition: 'Top 50', name: 'Nadine Khairunisa Firdaus', school: 'Cambridge International School' },
    { rank: 28, recognition: 'Top 50', name: 'Lana Hassan Issa', school: 'Rafic Hariri High School' },
    { rank: 29, recognition: 'Top 50', name: 'Nookala Akshita', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 30, recognition: 'Top 50', name: 'Koushani Paul', school: 'Global City International School' },
    { rank: 31, recognition: 'Top 50', name: 'Samanvii Botla', school: 'Suchitra Academy International School' },
    { rank: 32, recognition: 'Top 50', name: 'Akshita Singh', school: 'DAV Public School, airoli' },
    { rank: 33, recognition: 'Top 50', name: 'Pranavi Kaushik', school: 'Bright Riders School' },
    { rank: 34, recognition: 'Top 50', name: 'Geet Raisinghani', school: 'Nalanda Public School' },
    { rank: 35, recognition: 'Top 50', name: 'Abilash Selvam', school: 'Bright Riders School' },
    { rank: 36, recognition: 'Top 50', name: 'Valerio Pérez', school: 'Gokkusagi Schools İzmir' },
    { rank: 37, recognition: 'Top 50', name: 'Chaitanya Jaiswal', school: 'Thakur Public School' },
    { rank: 38, recognition: 'Top 50', name: 'Suyaash Khandelia', school: 'Suchitra Academy International School' },
    { rank: 39, recognition: 'Top 50', name: 'Abdel Majid', school: 'Rafic Hariri High School' },
    { rank: 40, recognition: 'Top 50', name: 'Ibrahim Waseem Abou Zahr', school: 'Rafic Hariri High School' },
    { rank: 41, recognition: 'Top 50', name: 'Charan Tej Bandike', school: 'Reqelford International School' },
    { rank: 42, recognition: 'Top 50', name: 'Abigail Mbwameh Akundo', school: 'American International School of Yaounde' },
    { rank: 43, recognition: 'Top 50', name: 'Anshika', school: 'The Cambridge School' },
    { rank: 44, recognition: 'Top 50', name: 'Priyanshu Vadariya', school: 'AMNS International School' },
    { rank: 45, recognition: 'Top 50', name: 'Neiwa Pithwa', school: 'HPC Bilinguale Grundschule | Kindercoaching & Deeper Learning' },
    { rank: 46, recognition: 'Top 50', name: 'Thirukkovalluri Arjun', school: 'The Hyderabad Public School' },
    { rank: 47, recognition: 'Top 50', name: 'Polina Protopopova', school: 'British International School' },
    { rank: 48, recognition: 'Top 50', name: 'Gunasagar Y. Et', school: 'B.H.P.S ( ಬಾಪು ಹಿರಿಯ ಪ್ರಾಥಮಿಕ ಪಾಠಶಾಲೆ)' },
    { rank: 49, recognition: 'Top 50', name: 'Jimena', school: 'Gökkuşağı Koleji' },
    { rank: 50, recognition: 'Top 50', name: 'Shrey Rahul Shidhaye', school: 'Kothari International School, Pune' },
  ],
};
