// IMC 2025-26 Finals — rankings data (8 grades × 50 ranks)
// Generated from IMC_2025-26_Website_Data.csv (post-merge of new additions, school names normalized)

window.IMC_DATA = {
  3: [
    { rank: 1, recognition: 'Topper', name: 'Vihaan Shah', school: 'Gem Genesis International School, Ahmedabad' },
    { rank: 2, recognition: 'Top 3', name: 'Avani Santosh More Patil', school: 'Bright Riders School' },
    { rank: 3, recognition: 'Top 3', name: 'Dheer Rawell', school: 'JBCN International School, Mulund' },
    { rank: 4, recognition: 'Top 10', name: 'Darshana', school: 'B V Bhavan\'s Rajaji Vidyashram' },
    { rank: 5, recognition: 'Top 10', name: 'Keshav Wadhwani', school: 'Oes International School, Vashi' },
    { rank: 6, recognition: 'Top 10', name: 'Samik', school: 'Shiv Nadar' },
    { rank: 7, recognition: 'Top 10', name: 'Aviraj Gupta', school: 'Thakur Public School' },
    { rank: 8, recognition: 'Top 10', name: 'Anushka Nikam', school: 'Veer Bhagat Singh International School, Malad West' },
    { rank: 9, recognition: 'Top 10', name: 'Simone Elise C. Tan To', school: 'Singapore School Manila' },
    { rank: 10, recognition: 'Top 10', name: 'Manthan S Shinde', school: 'Bright Riders School' },
    { rank: 11, recognition: 'Top 25', name: 'Atharv', school: 'Delhi Public School Rohini' },
    { rank: 12, recognition: 'Top 25', name: 'Yuvaan Srivastava', school: 'CMS Aliganj Campus I' },
    { rank: 13, recognition: 'Top 25', name: 'Dhruv Mittal', school: 'Suchitra Academy International School' },
    { rank: 14, recognition: 'Top 25', name: 'Ethan Macwan', school: 'Gems Genesis International School' },
    { rank: 15, recognition: 'Top 25', name: 'Sankalp Palaskar', school: 'Challenger Public School, Pune MH' },
    { rank: 16, recognition: 'Top 25', name: 'Darsh', school: 'CMS Aliganj Campus I' },
    { rank: 17, recognition: 'Top 25', name: 'Virat Bhardwaj', school: 'Delhi Public School Rohini' },
    { rank: 18, recognition: 'Top 25', name: 'Aniket Kumar', school: 'Delhi Public School Rohini' },
    { rank: 19, recognition: 'Top 25', name: 'Senthuran. Ka', school: 'The Optimus Public School, Sevagoundanur' },
    { rank: 20, recognition: 'Top 25', name: 'Shivaanya Nagpal', school: 'Delhi Public School Rohini' },
    { rank: 21, recognition: 'Top 25', name: 'Tanya Shree', school: 'Podar International School Besa Nagpur' },
    { rank: 22, recognition: 'Top 25', name: 'Dhrihaan Gupta', school: 'Shiv Nadar School, Chennai' },
    { rank: 23, recognition: 'Top 25', name: 'Kiaan Mehra', school: 'Lancers International School' },
    { rank: 24, recognition: 'Top 25', name: 'Fahima Naaz Quadri', school: 'Sunrise English Private School' },
    { rank: 25, recognition: 'Top 25', name: 'Reyansh Josyula', school: 'Kothari International School, Pune' },
    { rank: 26, recognition: 'Top 50', name: 'Mirayah', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 27, recognition: 'Top 50', name: 'Selim Anwar Mahmoud', school: 'Kipling School' },
    { rank: 28, recognition: 'Top 50', name: 'Kartikeya Nanda', school: 'Jasudben M L School' },
    { rank: 29, recognition: 'Top 50', name: 'Viraj Gupta', school: 'Delhi Public School Rohini' },
    { rank: 30, recognition: 'Top 50', name: 'Amay Singal', school: 'Bluebells School International' },
    { rank: 31, recognition: 'Top 50', name: 'Avyaan Dalal', school: 'Delhi Public School Rohini' },
    { rank: 32, recognition: 'Top 50', name: 'Devaansh Vikram Singh', school: 'Bright Riders School' },
    { rank: 33, recognition: 'Top 50', name: 'Vikramaditya Gupta', school: 'Delhi Public School Rohini' },
    { rank: 34, recognition: 'Top 50', name: 'Adhrit Narula', school: 'Delhi Public School Rohini' },
    { rank: 35, recognition: 'Top 50', name: 'Yatharth', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 36, recognition: 'Top 50', name: 'Natasha Sandi', school: 'Bright Riders School' },
    { rank: 37, recognition: 'Top 50', name: 'Reyansh Sinha', school: 'Challenger Public School - Pimple Saudagar' },
    { rank: 38, recognition: 'Top 50', name: 'Kirtisha.V', school: 'The Lords\' International School' },
    { rank: 39, recognition: 'Top 50', name: 'Swojas Pritam Kondalwar', school: 'Bhartiya Vidya Bhavan\'s' },
    { rank: 40, recognition: 'Top 50', name: 'Nivasini Dhevi V', school: 'Wellsprings Academy | Best CBSE School in Bengaluru' },
    { rank: 41, recognition: 'Top 50', name: 'Nathan 3B', school: 'Lancers International School' },
    { rank: 42, recognition: 'Top 50', name: 'Ira Chinmay Baxi', school: 'Deens Academy' },
    { rank: 43, recognition: 'Top 50', name: 'Anika', school: 'Birla Open Minds International School' },
    { rank: 44, recognition: 'Top 50', name: 'Pranika Bansal', school: 'Delhi Public School Rohini' },
    { rank: 45, recognition: 'Top 50', name: 'Liyaansh R Shetty', school: 'Navkis Educational Center, Gokula Campus' },
    { rank: 46, recognition: 'Top 50', name: 'Sharabh Sivabalan', school: 'Alphabet International School' },
    { rank: 47, recognition: 'Top 50', name: 'Aadvik Gupta', school: 'Children\'s Academy - Ghodbunder Road Campus' },
    { rank: 48, recognition: 'Top 50', name: 'Sharvin Praneet Mhaskar', school: 'Delhi Public School' },
    { rank: 49, recognition: 'Top 50', name: 'Saanvi Vats', school: 'Delhi Public School Rohini' },
    { rank: 50, recognition: 'Top 50', name: 'Manuja Milind Bhadane', school: 'Challenger Public School - Pimple Saudagar' },
  ],
  4: [
    { rank: 1, recognition: 'Topper', name: 'Yuxi Lin', school: 'Singapore School Manila' },
    { rank: 2, recognition: 'Top 3', name: 'Aaryav Taneja', school: 'Shiv Nadar School, Faridabad' },
    { rank: 3, recognition: 'Top 3', name: 'Yuvan Sobti', school: 'Shiv Nadar School (Faridabad)' },
    { rank: 4, recognition: 'Top 10', name: 'Unaisa Fatima', school: 'Alhussan International School "Yanbu"' },
    { rank: 5, recognition: 'Top 10', name: 'Aditi Rtavari Suri', school: 'Shiv Nadar School' },
    { rank: 6, recognition: 'Top 10', name: 'Inika Gupta John', school: 'DPS Vasant Kunj' },
    { rank: 7, recognition: 'Top 10', name: 'Jofhitha', school: 'The PSBB Millennium School' },
    { rank: 8, recognition: 'Top 10', name: 'Gauthamiyuktha Jampa', school: 'Agraganya Public School' },
    { rank: 9, recognition: 'Top 10', name: 'Amay Minocha', school: 'Delhi Public School Rohini' },
    { rank: 10, recognition: 'Top 10', name: 'Md Suhail Rahman', school: 'Australian International School' },
    { rank: 11, recognition: 'Top 25', name: 'Samaira Aggarwal', school: 'Amity International School' },
    { rank: 12, recognition: 'Top 25', name: 'Ved Jain', school: 'Freedom International School' },
    { rank: 13, recognition: 'Top 25', name: 'Ronav Shahani', school: 'Amity International School' },
    { rank: 14, recognition: 'Top 25', name: 'Mahi', school: 'Army Public School' },
    { rank: 15, recognition: 'Top 25', name: 'Pihu Choudhary', school: 'NIST College' },
    { rank: 16, recognition: 'Top 25', name: 'Hemakshi Ravi Keshan', school: 'AMNS International School' },
    { rank: 17, recognition: 'Top 25', name: 'Aroom', school: 'Vista International School, Hyderabad' },
    { rank: 18, recognition: 'Top 25', name: 'Asmi', school: 'Podar International School Thane (CBSE)' },
    { rank: 19, recognition: 'Top 25', name: 'Mahathi', school: 'Pon Vidyashram Group of Senior Secondary Schools' },
    { rank: 20, recognition: 'Top 25', name: 'Parth Vaibhav Chavan', school: 'The Lexicon International School Wagholi' },
    { rank: 21, recognition: 'Top 25', name: 'Bohao Shi', school: 'Singapore School Manila' },
    { rank: 22, recognition: 'Top 25', name: 'Kanisha', school: 'Birla Open Minds International School' },
    { rank: 23, recognition: 'Top 25', name: 'Ahana', school: 'Birla Open Minds International School' },
    { rank: 24, recognition: 'Top 25', name: 'Durvank Ghate', school: 'Challenger Public School, Pune MH' },
    { rank: 25, recognition: 'Top 25', name: 'Havish Rakesh', school: 'Sv High Global School' },
    { rank: 26, recognition: 'Top 50', name: 'Avani Pulivendala', school: 'Bright Riders School' },
    { rank: 27, recognition: 'Top 50', name: 'Reyaan Jain', school: 'AMNS International School' },
    { rank: 28, recognition: 'Top 50', name: 'Hariaksha Vishwanathan', school: 'AMNS International School, Hazira, Surat' },
    { rank: 29, recognition: 'Top 50', name: 'Advika Sharma', school: 'Delhi Public School Rohini' },
    { rank: 30, recognition: 'Top 50', name: 'Kiyan Sachdeva', school: 'Lancers International School' },
    { rank: 31, recognition: 'Top 50', name: 'Marcus Koistinen', school: 'EEBA' },
    { rank: 32, recognition: 'Top 50', name: 'Stuti Chaturvedi', school: 'CMS Aliganj Campus I' },
    { rank: 33, recognition: 'Top 50', name: 'Timofei Khavroshin', school: 'Gokkusagi Schools İzmir' },
    { rank: 34, recognition: 'Top 50', name: 'Mourad Mohamed Abd Elaziz Ahmed Ismail', school: 'Smart Village School' },
    { rank: 35, recognition: 'Top 50', name: 'Sia Jyoti', school: 'Tagore International School' },
    { rank: 36, recognition: 'Top 50', name: 'Gauravi Devadiga', school: 'Thakur Public School' },
    { rank: 37, recognition: 'Top 50', name: 'Samyak Kansal', school: 'Amity International School' },
    { rank: 38, recognition: 'Top 50', name: 'Atmikha Arun', school: 'Bhavans Pearl Wisdom School Sharjah' },
    { rank: 39, recognition: 'Top 50', name: 'Arshan', school: 'Sparkles International School | Best CBSE School in Gulbarga' },
    { rank: 40, recognition: 'Top 50', name: 'Ishanvi Singh', school: 'CMS Aliganj Campus I' },
    { rank: 41, recognition: 'Top 50', name: 'Anvi Badhan', school: 'DAV Public School, Airoli' },
    { rank: 42, recognition: 'Top 50', name: 'Trisha Yadav', school: 'CMS Aliganj Campus I' },
    { rank: 43, recognition: 'Top 50', name: 'Sayona Awasthi', school: 'Birla Open Minds International School' },
    { rank: 44, recognition: 'Top 50', name: 'Namasvi', school: 'Birla Open Minds International School' },
    { rank: 45, recognition: 'Top 50', name: 'Aarav', school: 'Agarwal Vidyalaya and Junior College' },
    { rank: 46, recognition: 'Top 50', name: 'Sophia Yehia Khafagi', school: 'Kipling School' },
    { rank: 47, recognition: 'Top 50', name: 'Sia Agnihotri', school: 'Birla Open Minds International School' },
    { rank: 48, recognition: 'Top 50', name: 'Enaya Chugh', school: 'Gems Genesis International School' },
    { rank: 49, recognition: 'Top 50', name: 'Aahan Maity', school: 'Suchitra Academy International School' },
    { rank: 50, recognition: 'Top 50', name: 'Prabhas Mishra', school: 'Podar International School' },
  ],
  5: [
    { rank: 1, recognition: 'Topper', name: 'Fiona Dey', school: 'Bharatiya Vidya Bhavan\'s V M Public School, Vadodara' },
    { rank: 2, recognition: 'Top 3', name: 'Azara Singh', school: 'Greenwood High - Sarjapur' },
    { rank: 3, recognition: 'Top 3', name: 'Moksh Nirav Khatri', school: 'Ramniwas Bajaj English High School' },
    { rank: 4, recognition: 'Top 10', name: 'S.Sanjana', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 5, recognition: 'Top 10', name: 'Syed Rehan', school: 'St. Mary\'s Catholic High School Fujairah, UAE.' },
    { rank: 6, recognition: 'Top 10', name: 'Rudra Bhonsle', school: 'Bharatiya Vidya Bhavan\'s V M Public School, Vadodara' },
    { rank: 7, recognition: 'Top 10', name: 'Anaya Agrawal', school: 'Thakur Public School' },
    { rank: 8, recognition: 'Top 10', name: 'Jules Alexander L. Lopez', school: 'Singapore School Manila' },
    { rank: 9, recognition: 'Top 10', name: 'Agasthya Manjunatha', school: 'Prarthana World School' },
    { rank: 10, recognition: 'Top 10', name: 'Soumajit Paul', school: 'Mentor International School' },
    { rank: 11, recognition: 'Top 25', name: 'A Keerthi Sri', school: 'Apex Pon Vidyashram Velachery' },
    { rank: 12, recognition: 'Top 25', name: 'Riyansh Santosh Dhait', school: 'Kothari International School, Pune' },
    { rank: 13, recognition: 'Top 25', name: 'Tanisha', school: 'Vista International School' },
    { rank: 14, recognition: 'Top 25', name: 'Arham Jahangir Mohammed', school: 'Suchitra Academy International School' },
    { rank: 15, recognition: 'Top 25', name: 'Bhavishya', school: 'Birla Open Minds International School' },
    { rank: 16, recognition: 'Top 25', name: 'Tuvisha', school: 'DL DAV Model School, Tp Block, Pitampura, Delhi' },
    { rank: 17, recognition: 'Top 25', name: 'Ikshanaa Dutta', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 18, recognition: 'Top 25', name: 'Saanvi Talwar', school: 'Delhi Public School Rohini' },
    { rank: 19, recognition: 'Top 25', name: 'Bhupathiraju Nithya Saanvika', school: 'Birla Open Minds International School' },
    { rank: 20, recognition: 'Top 25', name: 'Vedant Gupta', school: 'Delhi Public School Rohini' },
    { rank: 21, recognition: 'Top 25', name: 'Shruti . Ashru . Wakode', school: 'Challenger Public School - Pimple Saudagar' },
    { rank: 22, recognition: 'Top 25', name: 'Hana Medlova', school: 'Spojená Škola, Pankúchova 6, Bratislava' },
    { rank: 23, recognition: 'Top 25', name: 'D Siya', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 24, recognition: 'Top 25', name: 'Ved Sawant', school: 'Challenger Public School, Pune MH' },
    { rank: 25, recognition: 'Top 25', name: 'Aarav Goel', school: 'Delhi Public School Rohini' },
    { rank: 26, recognition: 'Top 50', name: 'Yuven Gain', school: 'Inventure Academy' },
    { rank: 27, recognition: 'Top 50', name: 'Saathwik Puttagunta', school: 'Army Public School' },
    { rank: 28, recognition: 'Top 50', name: 'Ayaan Bongu', school: 'Suchitra Academy International School' },
    { rank: 29, recognition: 'Top 50', name: 'Vaidik Jindal', school: 'Bright Riders School' },
    { rank: 30, recognition: 'Top 50', name: 'Jainil Modi', school: 'AMNS International School' },
    { rank: 31, recognition: 'Top 50', name: 'Shaurya Ganesh Prabhu', school: 'Thakur Public School' },
    { rank: 32, recognition: 'Top 50', name: 'Cadmiel M Joby', school: 'Bapuji Higher Primary English School' },
    { rank: 33, recognition: 'Top 50', name: 'Joshua.Thysheril', school: 'Inventure Academy' },
    { rank: 34, recognition: 'Top 50', name: 'Vaikhari Swanand Marulkar', school: 'HPC International School' },
    { rank: 35, recognition: 'Top 50', name: 'Saimahesh Rajavel. R', school: 'The PSBB Millennium School' },
    { rank: 36, recognition: 'Top 50', name: 'Cazmir Singh', school: 'Lancers International School' },
    { rank: 37, recognition: 'Top 50', name: 'Anjali M.', school: 'Navkis Educational Center, Gokula Campus' },
    { rank: 38, recognition: 'Top 50', name: 'M. Muhammed Fuzail', school: 'Velankani Public School' },
    { rank: 39, recognition: 'Top 50', name: 'Arnav', school: 'Ramjas Public School' },
    { rank: 40, recognition: 'Top 50', name: 'Ali Mohamed Nabil', school: 'Kipling School' },
    { rank: 41, recognition: 'Top 50', name: 'Amarnath Ghora', school: 'Army Public School' },
    { rank: 42, recognition: 'Top 50', name: 'Arun Prakash', school: 'CP Goenka International School' },
    { rank: 43, recognition: 'Top 50', name: 'Riyan Jain', school: 'Bharatiya Vidya Bhavan\'s V M Public School, Vadodara' },
    { rank: 44, recognition: 'Top 50', name: 'Ridhaan Aggarwal', school: 'Delhi Public School Rohini' },
    { rank: 45, recognition: 'Top 50', name: 'Avyukt Mahadik', school: 'CP Goenka International School' },
    { rank: 46, recognition: 'Top 50', name: 'Deekshita R', school: 'KSN Senior Secondary School (CBSE)' },
    { rank: 47, recognition: 'Top 50', name: 'Joshua Abhishek', school: 'Sv High Global School Arumbakkam (Cambridge)' },
    { rank: 48, recognition: 'Top 50', name: 'Kanali', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 49, recognition: 'Top 50', name: 'Mohammad Rayyan', school: 'Bright Riders School' },
    { rank: 50, recognition: 'Top 50', name: 'Ruhaan', school: 'Birla Open Minds International School' },
  ],
  6: [
    { rank: 1, recognition: 'Topper', name: 'Jyothy Pagadala', school: 'Birla Open Minds International School' },
    { rank: 2, recognition: 'Top 3', name: 'Mayank Bansal', school: 'GD Goenka Public School' },
    { rank: 3, recognition: 'Top 3', name: 'Sreehari Sijil', school: 'Bhavan\'s Pearl Wisdom School' },
    { rank: 4, recognition: 'Top 10', name: 'Ruthvika Vankadhara', school: 'Bright Riders School' },
    { rank: 5, recognition: 'Top 10', name: 'Labdhi Manoj Jain', school: 'AMNS International School' },
    { rank: 6, recognition: 'Top 10', name: 'Vivaan Prithyani', school: 'Kothari International School, Pune' },
    { rank: 7, recognition: 'Top 10', name: 'Kaushik', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 8, recognition: 'Top 10', name: 'Ishita', school: 'HPC International School' },
    { rank: 9, recognition: 'Top 10', name: 'Jason Jebezlin. B', school: 'Christwood School, Ponmar' },
    { rank: 10, recognition: 'Top 10', name: 'Eshan Gullipalli', school: 'Birla Open Minds International School' },
    { rank: 11, recognition: 'Top 25', name: 'Omkaar Jagyasi', school: 'Gem Genesis International School, Ahmedabad' },
    { rank: 12, recognition: 'Top 25', name: 'Kiyan Mohamed Mostafa', school: 'Smart Village School' },
    { rank: 13, recognition: 'Top 25', name: 'Debanshi N Mandela', school: 'Bharatiya Vidya Bhavan\'s Vallabhram Mehta Public School' },
    { rank: 14, recognition: 'Top 25', name: 'Rachana Tulsidas Naik', school: 'Bharatiya Vidya Bhavan\'s Narayan Bandekar School,Upasnagar , Goa ,403726' },
    { rank: 15, recognition: 'Top 25', name: 'Gohita Vrinda Medandrao', school: 'Birla Open Minds International School' },
    { rank: 16, recognition: 'Top 25', name: 'K. Shrilekha Siddi Priya', school: 'Suchitra Academy International School' },
    { rank: 17, recognition: 'Top 25', name: 'Soham', school: 'Savitridevi Hariram Agarwal International School' },
    { rank: 18, recognition: 'Top 25', name: 'Sanvi Manish Bhawalkar', school: 'Podar International School Besa, Nagpur' },
    { rank: 19, recognition: 'Top 25', name: 'Aaradhya Singh', school: 'Birla Open Minds International School' },
    { rank: 20, recognition: 'Top 25', name: 'Muhammad Ibrahim', school: 'Australian International School' },
    { rank: 21, recognition: 'Top 25', name: 'Vihaan Mittal', school: 'Global City International School' },
    { rank: 22, recognition: 'Top 25', name: 'Anish Ankireddypalle', school: 'Delhi Public School, Nadergul' },
    { rank: 23, recognition: 'Top 25', name: 'Kodam.Sai Sindu Priya', school: 'Suchitra Academy International School' },
    { rank: 24, recognition: 'Top 25', name: 'Hridhaan Ghosh', school: 'Bright Riders School' },
    { rank: 25, recognition: 'Top 25', name: 'Aditi Nilesh Halde', school: 'CP Goenka International School' },
    { rank: 26, recognition: 'Top 50', name: 'Shirish .N', school: 'Suchitra Academy International School' },
    { rank: 27, recognition: 'Top 50', name: 'Satvik Vatsa', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 28, recognition: 'Top 50', name: 'Hetaksh', school: 'Shri Ram Centennial School' },
    { rank: 29, recognition: 'Top 50', name: 'Liam Reign Y. Chuco', school: 'Singapore School Manila' },
    { rank: 30, recognition: 'Top 50', name: 'Aarushi Botchu', school: 'Birla Open Minds International School' },
    { rank: 31, recognition: 'Top 50', name: 'Prisha Romil Bavishi', school: 'Savitridevi Hariram Agarwal International School' },
    { rank: 32, recognition: 'Top 50', name: 'Aman Suraj', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 33, recognition: 'Top 50', name: 'Kartavya Nahata', school: 'DPS Whitefield Mallasandra' },
    { rank: 34, recognition: 'Top 50', name: 'Avani Tathe', school: 'Birla Open Minds International School' },
    { rank: 35, recognition: 'Top 50', name: 'Rayansh Mehra', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 36, recognition: 'Top 50', name: 'Shriya Priyesh', school: 'New Millennium School' },
    { rank: 37, recognition: 'Top 50', name: 'Spandan', school: 'N.v Chinmaya Vidyalaya Shegaon' },
    { rank: 38, recognition: 'Top 50', name: 'Trinay', school: 'Army Public School' },
    { rank: 39, recognition: 'Top 50', name: 'Charvi Mathur', school: 'Kanakia International School, Bhayandar (CBSE Board)' },
    { rank: 40, recognition: 'Top 50', name: 'Archeesha Srivastava', school: 'Bright Riders School' },
    { rank: 41, recognition: 'Top 50', name: 'Archit Yadav', school: 'CMS Aliganj Campus I' },
    { rank: 42, recognition: 'Top 50', name: 'Myriam Santina', school: 'Rafic Hariri High School' },
    { rank: 43, recognition: 'Top 50', name: 'Shreyaan Gorain', school: 'Delhi Public School Electronic City' },
    { rank: 44, recognition: 'Top 50', name: 'Manan Bajoria', school: 'The Newtown School' },
    { rank: 45, recognition: 'Top 50', name: 'Chitrangana Singh', school: 'Bright Riders School' },
    { rank: 46, recognition: 'Top 50', name: 'Aaral', school: 'Birla Open Minds International School' },
    { rank: 47, recognition: 'Top 50', name: 'Delisha Dnyaneshwar Patil', school: 'Bright Riders School' },
    { rank: 48, recognition: 'Top 50', name: 'Ateeksh Atishay', school: 'DPS Ecity' },
    { rank: 49, recognition: 'Top 50', name: 'Arya Prasad Rana', school: 'Army Public School' },
    { rank: 50, recognition: 'Top 50', name: 'Pratyush Pacheria', school: 'Ramniwas Bajaj English High School' },
  ],
  7: [
    { rank: 1, recognition: 'Topper', name: 'Mrunmayee Puranik', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 2, recognition: 'Top 3', name: 'Arav Choudhary', school: 'Birla Open Minds International School' },
    { rank: 3, recognition: 'Top 3', name: 'Vaibhav Suna', school: 'Airson School' },
    { rank: 4, recognition: 'Top 10', name: 'Aarush R', school: 'Ramniwas Bajaj English High School' },
    { rank: 5, recognition: 'Top 10', name: 'Vimal Manoj Kumar', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 6, recognition: 'Top 10', name: 'Arsh Roshan', school: 'Bright Riders School' },
    { rank: 7, recognition: 'Top 10', name: 'Aadhya Nilesh Piraji', school: 'Mentor International School' },
    { rank: 8, recognition: 'Top 10', name: 'Parsa', school: 'HPC International School' },
    { rank: 9, recognition: 'Top 10', name: 'Naira Narang', school: 'Bluebells School International' },
    { rank: 10, recognition: 'Top 10', name: 'Urvi Santosh More Patil', school: 'Bright Riders School' },
    { rank: 11, recognition: 'Top 25', name: 'Abhigyan Sinha', school: 'Navkis Educational Centre, Bangalore' },
    { rank: 12, recognition: 'Top 25', name: 'Aagneya Prasad', school: 'Sunrise English Private School' },
    { rank: 13, recognition: 'Top 25', name: 'Aniket Agarwal', school: 'AMNS International School, Hazira,Surat,India' },
    { rank: 14, recognition: 'Top 25', name: 'Tanish Trivedi', school: 'Kanakia International School, Bhayandar (CBSE Board)' },
    { rank: 15, recognition: 'Top 25', name: 'Kavimugilan S', school: 'Delhi Public School, Nadergul' },
    { rank: 16, recognition: 'Top 25', name: 'Zhijie Zhang', school: 'Singapore School Manila' },
    { rank: 17, recognition: 'Top 25', name: 'Arnav Mishra', school: 'Delhi Public School Rohini' },
    { rank: 18, recognition: 'Top 25', name: 'Vihan', school: 'Army Public School' },
    { rank: 19, recognition: 'Top 25', name: 'Advik Patra', school: 'Mentor International School' },
    { rank: 20, recognition: 'Top 25', name: 'Hari Charan Neralla', school: 'Bright Riders School' },
    { rank: 21, recognition: 'Top 25', name: 'Aaria Gupta', school: 'DPS East Bengaluru' },
    { rank: 22, recognition: 'Top 25', name: 'Randa Mohiddeen Mneimne', school: 'Rafic Hariri High School' },
    { rank: 23, recognition: 'Top 25', name: 'Yatharth Sharma', school: 'Delhi Public School Rohini' },
    { rank: 24, recognition: 'Top 25', name: 'Viraj', school: 'Bright Riders School' },
    { rank: 25, recognition: 'Top 25', name: 'Srihari S', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 26, recognition: 'Top 50', name: 'Manvitha Navin', school: 'Shiv Nadar School, Chennai' },
    { rank: 27, recognition: 'Top 50', name: 'Akshara Nagraj Nadgouda', school: 'Bright Riders School' },
    { rank: 28, recognition: 'Top 50', name: 'Aradhya Chaturvedi', school: 'CMS Aliganj Campus I' },
    { rank: 29, recognition: 'Top 50', name: 'Reyansh Nunna', school: 'Birla Open Minds International School' },
    { rank: 30, recognition: 'Top 50', name: 'Shivaansh Sinha', school: 'Challenger Public School, Pune MH' },
    { rank: 31, recognition: 'Top 50', name: 'Naga Smaran Reddy Garudagari', school: 'Birla Open Minds International School' },
    { rank: 32, recognition: 'Top 50', name: 'Darsh Vignesh', school: 'KSN Senior Secondary School (CBSE)' },
    { rank: 33, recognition: 'Top 50', name: 'Aakarshika Agarwal', school: 'La Martiniere Girls\' College' },
    { rank: 34, recognition: 'Top 50', name: 'Haardit Bhandari', school: 'The Premia Academy, Hyderabad' },
    { rank: 35, recognition: 'Top 50', name: 'Charmi', school: 'DPS' },
    { rank: 36, recognition: 'Top 50', name: 'Prateek Singh', school: 'Army Public School' },
    { rank: 37, recognition: 'Top 50', name: 'Aarvi Dhiraj Patel', school: 'Ramniwas Bajaj English High School' },
    { rank: 38, recognition: 'Top 50', name: 'Aanya Choudhury', school: 'Delhi Public School, Nadergul' },
    { rank: 39, recognition: 'Top 50', name: 'Vedika Dangi', school: 'Vinayam Public School' },
    { rank: 40, recognition: 'Top 50', name: 'Manas', school: 'Bluebells School International' },
    { rank: 41, recognition: 'Top 50', name: 'Kritika Chopde', school: 'AMNS International School' },
    { rank: 42, recognition: 'Top 50', name: 'Ishaan Balasubramanian', school: 'Sv High Global School' },
    { rank: 43, recognition: 'Top 50', name: 'R Ajay', school: 'DMI St. Joseph Global School' },
    { rank: 44, recognition: 'Top 50', name: 'Manan Paijwar', school: 'CMS Aliganj Campus I' },
    { rank: 45, recognition: 'Top 50', name: 'Bharathi S', school: 'DAV Public School, Airoli' },
    { rank: 46, recognition: 'Top 50', name: 'Abdul Raqeeb Mohammed', school: 'Alhussan International School "Yanbu"' },
    { rank: 47, recognition: 'Top 50', name: 'Aanik Seth', school: 'Lancers International School' },
    { rank: 48, recognition: 'Top 50', name: 'Tseday', school: 'Reach International Centre of Education - Agona Campus' },
    { rank: 49, recognition: 'Top 50', name: 'Krisheth Rajendran Saravanan', school: 'Bright Riders School' },
    { rank: 50, recognition: 'Top 50', name: 'Lavanya Thawre', school: 'Podar International School , Besa , Nagpur' },
  ],
  8: [
    { rank: 1, recognition: 'Topper', name: 'Tirth Doshi', school: 'Savitridevi Hariram Agarwal International School' },
    { rank: 2, recognition: 'Top 3', name: 'Banaj Bansal', school: 'Ramniwas Bajaj English High School' },
    { rank: 3, recognition: 'Top 3', name: 'Tianna Sharma', school: 'Lancers International School - IB School in Gurgaon' },
    { rank: 4, recognition: 'Top 10', name: 'Arun', school: 'Birla Open Minds International School' },
    { rank: 5, recognition: 'Top 10', name: 'Archita Sawanak', school: 'CMS Aliganj Campus I' },
    { rank: 6, recognition: 'Top 10', name: 'Aarna Bist', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 7, recognition: 'Top 10', name: 'Dagmawi', school: 'Reach International Center of Education' },
    { rank: 8, recognition: 'Top 10', name: 'Anvika Shetty', school: 'Global City International School' },
    { rank: 9, recognition: 'Top 10', name: 'Aarika Jain', school: 'Delhi Public School Rohini' },
    { rank: 10, recognition: 'Top 10', name: 'Alisha', school: 'Bluebells School International' },
    { rank: 11, recognition: 'Top 25', name: 'Raniya Mumtaz', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 12, recognition: 'Top 25', name: 'Perla Wissam El Hajj', school: 'Rafic Hariri High School' },
    { rank: 13, recognition: 'Top 25', name: 'Maithil', school: 'Delhi Public School Electronic City' },
    { rank: 14, recognition: 'Top 25', name: 'Nikhilan Vasanthan', school: 'Global City International School' },
    { rank: 15, recognition: 'Top 25', name: 'Yeshas.H', school: 'Global City International School' },
    { rank: 16, recognition: 'Top 25', name: 'Aya Bassem Akra', school: 'Rafic Hariri High School' },
    { rank: 17, recognition: 'Top 25', name: 'Guhan Pannerkumar', school: 'Delhi Public School, Bangalore East' },
    { rank: 18, recognition: 'Top 25', name: 'N Kowshika', school: 'Maharishi Vidya Mandir Senior Secondary School' },
    { rank: 19, recognition: 'Top 25', name: 'Lohit', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 20, recognition: 'Top 25', name: 'Shreyasi Sinha', school: 'Navkis Educational Centre, Bangalore' },
    { rank: 21, recognition: 'Top 25', name: 'Mohammad El Hajj Chehade', school: 'Iklim High School' },
    { rank: 22, recognition: 'Top 25', name: 'Sanvi Sai Moharla', school: 'Delhi Public School, Bangalore East' },
    { rank: 23, recognition: 'Top 25', name: 'Aayush Kar', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 24, recognition: 'Top 25', name: 'Caren Habib Abdo', school: 'Rafic Hariri High School' },
    { rank: 25, recognition: 'Top 25', name: 'Kanishka Praveen', school: 'Global City International School' },
    { rank: 26, recognition: 'Top 50', name: 'Vihaan Anand', school: 'Delhi Public School Electronic City' },
    { rank: 27, recognition: 'Top 50', name: 'R. Yuvan Kumar', school: 'Keren Public School கேரன்ஸ் பப்ளிக் பள்ளி' },
    { rank: 28, recognition: 'Top 50', name: 'Vihaan Patkar', school: 'DAV Public School, Airoli' },
    { rank: 29, recognition: 'Top 50', name: 'Diptanshu Sunil Saraf', school: 'Bright Riders School' },
    { rank: 30, recognition: 'Top 50', name: 'Jaiveer Wadhwani', school: 'Oes International School, Vashi' },
    { rank: 31, recognition: 'Top 50', name: 'Martin Chen', school: 'Singapore School Manila' },
    { rank: 32, recognition: 'Top 50', name: 'Avinika Patel', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 33, recognition: 'Top 50', name: 'Hasset Fikreselassie', school: 'Reach International Centre of Education - Agona Campus' },
    { rank: 34, recognition: 'Top 50', name: 'Parindi Rajeshkumar Vaghasiya', school: 'Bright Riders School' },
    { rank: 35, recognition: 'Top 50', name: 'M. Ashaj Zain', school: 'Podar International School, Amravati 2' },
    { rank: 36, recognition: 'Top 50', name: 'Royce Fitzgerald L. Co', school: 'Singapore School Manila' },
    { rank: 37, recognition: 'Top 50', name: 'Suvarna Bachhuka', school: 'AMNS International School' },
    { rank: 38, recognition: 'Top 50', name: 'A Deekshitha Priya', school: 'Apex Pon Vidyashram Velachery' },
    { rank: 39, recognition: 'Top 50', name: 'Karim Habib Abdo', school: 'Rafic Hariri High School' },
    { rank: 40, recognition: 'Top 50', name: 'Swarit Shukla', school: 'Shri Indradeo Singh International School' },
    { rank: 41, recognition: 'Top 50', name: 'Devansh Ray Chaudhuri', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 42, recognition: 'Top 50', name: 'Manya V', school: 'Agarwal Vidyalaya and Junior College' },
    { rank: 43, recognition: 'Top 50', name: 'Swara Gandhi', school: 'Kanakia International School, Bhayandar (CBSE Board)' },
    { rank: 44, recognition: 'Top 50', name: 'Maanav Rai', school: 'Army Public School, Noida' },
    { rank: 45, recognition: 'Top 50', name: 'Vaibhav Raj', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 46, recognition: 'Top 50', name: 'Nikhitha', school: 'Bright Riders School' },
    { rank: 47, recognition: 'Top 50', name: 'Haya Wazne', school: 'Wellspring Learning Community' },
    { rank: 48, recognition: 'Top 50', name: 'Mirav', school: 'Delhi Public School, Greater Faridabad' },
    { rank: 49, recognition: 'Top 50', name: 'Siya Patidar', school: 'Bright Riders School' },
    { rank: 50, recognition: 'Top 50', name: 'Mudit', school: 'Bluebells School International' },
  ],
  9: [
    { rank: 1, recognition: 'Topper', name: 'Paarth Gupta', school: 'Bluebells School International' },
    { rank: 2, recognition: 'Top 3', name: 'Sneh Shah', school: 'Thakur Public School' },
    { rank: 3, recognition: 'Top 3', name: 'Anamika Patel', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 4, recognition: 'Top 10', name: 'Pothula Karthik Sai', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 5, recognition: 'Top 10', name: 'Harshita Jain', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 6, recognition: 'Top 10', name: 'Anika Pariza Ashraf', school: 'St. Francis Xavier Girls High School' },
    { rank: 7, recognition: 'Top 10', name: 'Saisaurav Samanta', school: 'The Newtown School' },
    { rank: 8, recognition: 'Top 10', name: 'Ishaan', school: 'Delhi Public School, Bangalore East' },
    { rank: 9, recognition: 'Top 10', name: 'Aditya Narayan Adak', school: 'The Newtown School' },
    { rank: 10, recognition: 'Top 10', name: 'Balakrishna Iyer', school: 'DAV Public School, Airoli' },
    { rank: 11, recognition: 'Top 25', name: 'Yajas Vashistha', school: 'Global City International School' },
    { rank: 12, recognition: 'Top 25', name: 'Aarna Manish Keshwani', school: 'Podar International School, Badnera Road, Amravati' },
    { rank: 13, recognition: 'Top 25', name: 'Nidhish', school: 'Delhi Public School, Bangalore East' },
    { rank: 14, recognition: 'Top 25', name: 'Soumil Manna', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 15, recognition: 'Top 25', name: 'Divya Patil', school: 'Challenger Public School, Pune MH' },
    { rank: 16, recognition: 'Top 25', name: 'Hardik Pandit', school: 'Lancers International School' },
    { rank: 17, recognition: 'Top 25', name: 'Aadya Milind Bhoir', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 18, recognition: 'Top 25', name: 'Pavi Sinha', school: 'Delhi Public School Rohini' },
    { rank: 19, recognition: 'Top 25', name: 'Alwalid Rani Saleh', school: 'Rafic Hariri High School' },
    { rank: 20, recognition: 'Top 25', name: 'Aarav Kumar Singh', school: 'CMS Aliganj Campus I' },
    { rank: 21, recognition: 'Top 25', name: 'C.G.Shruthi', school: 'Pon Vidyashram Group of Senior Secondary Schools' },
    { rank: 22, recognition: 'Top 25', name: 'Seoyoon Bae', school: 'Lancers International School - IB School in Gurgaon' },
    { rank: 23, recognition: 'Top 25', name: 'Shaivi Sinha', school: 'Thakur Public School' },
    { rank: 24, recognition: 'Top 25', name: 'Saket Salil', school: 'Delhi Public School, Bangalore East' },
    { rank: 25, recognition: 'Top 25', name: 'Yaksh Agarwal', school: 'Suchitra Academy International School' },
    { rank: 26, recognition: 'Top 50', name: 'Keshav Sambhu', school: 'DAV Public School, Airoli' },
    { rank: 27, recognition: 'Top 50', name: 'Koppula Virinchi', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 28, recognition: 'Top 50', name: 'Mayol Wahengbam', school: 'Delhi Public School, Bangalore East' },
    { rank: 29, recognition: 'Top 50', name: 'Anish Anand', school: 'Deens Academy' },
    { rank: 30, recognition: 'Top 50', name: 'Yash Agrahari', school: 'St. Peter’s Convent School Sec 88, Greater Faridabad.' },
    { rank: 31, recognition: 'Top 50', name: 'Celine Abedul Rahman Santina', school: 'Rafic Hariri High School' },
    { rank: 32, recognition: 'Top 50', name: 'Aarav Siddharth Doshi', school: 'Bharatiya Vidya Bhavan\'s Vallabhram Mehta Public School' },
    { rank: 33, recognition: 'Top 50', name: 'Christian', school: 'British International School of Moscow 3' },
    { rank: 34, recognition: 'Top 50', name: 'Hunar Periwal', school: 'Kanakia International School, Bhayandar (CBSE Board)' },
    { rank: 35, recognition: 'Top 50', name: 'Kritika Tripathi', school: 'St. Peter’s Convent School Sec 88, Greater Faridabad.' },
    { rank: 36, recognition: 'Top 50', name: 'Keerat Singh Ponglia', school: 'Global City International School' },
    { rank: 37, recognition: 'Top 50', name: 'Aradhya Anant Upadhyay', school: 'Global City International School' },
    { rank: 38, recognition: 'Top 50', name: 'Aaliya Arora', school: 'AMNS International School, Surat' },
    { rank: 39, recognition: 'Top 50', name: 'Iniyan S', school: 'Keren Public School' },
    { rank: 40, recognition: 'Top 50', name: 'P Siddhanth Reddy', school: 'Suchitra Academy International School' },
    { rank: 41, recognition: 'Top 50', name: 'Samarth Vishalkumar Shah', school: 'Bharatiya Vidya Bhavan\'s Vallabhram Mehta Public School' },
    { rank: 42, recognition: 'Top 50', name: 'Jiya Jineshkumar Doshi', school: 'Bright Riders School' },
    { rank: 43, recognition: 'Top 50', name: 'Samarth Agarwal', school: 'Lancers International School' },
    { rank: 44, recognition: 'Top 50', name: 'Arpit Sharma', school: 'Delhi Public School Rohini' },
    { rank: 45, recognition: 'Top 50', name: 'Obasi Eret Michel Ntui', school: 'American International School of Yaounde' },
    { rank: 46, recognition: 'Top 50', name: 'Muthupandi', school: 'Keren Public School கேரன்ஸ் பப்ளிக் பள்ளி' },
    { rank: 47, recognition: 'Top 50', name: 'Avyukta G Rao', school: 'Sri Kumaran Children\'s Academy - CBSE Doddakallasandra' },
    { rank: 48, recognition: 'Top 50', name: 'Aadit Singh', school: 'Gems Genesis International School (Ggis)' },
    { rank: 49, recognition: 'Top 50', name: 'Ananya', school: 'Sunbeam Suncity (School & Hostel)' },
    { rank: 50, recognition: 'Top 50', name: 'Neeti Patel', school: 'Bharatiya Vidya Bhavan\'s Vallabhram Mehta Public School' },
  ],
  10: [
    { rank: 1, recognition: 'Topper', name: 'Purvesh Kapse', school: 'Podar International School Nagpur Besa' },
    { rank: 2, recognition: 'Top 3', name: 'Nicole Jessica Jagan', school: 'The Lords\' International School' },
    { rank: 3, recognition: 'Top 3', name: 'Areeba Fatima', school: 'Alhussan Int. School - Girls Section' },
    { rank: 4, recognition: 'Top 10', name: 'Arnav Verma', school: 'Delhi Public School, Navi Mumbai' },
    { rank: 5, recognition: 'Top 10', name: 'Anshika', school: 'The Cambridge School' },
    { rank: 6, recognition: 'Top 10', name: 'Kaushik R', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 7, recognition: 'Top 10', name: 'Aditi Patra', school: 'Mentor International School' },
    { rank: 8, recognition: 'Top 10', name: 'Anvita Mathur', school: 'Airson School' },
    { rank: 9, recognition: 'Top 10', name: 'Beren Aygür', school: 'Gökkuşağı Koleji' },
    { rank: 10, recognition: 'Top 10', name: 'Shaurya Saraf', school: 'Thakur Public School' },
    { rank: 11, recognition: 'Top 25', name: 'Sidhi Upadhyay', school: 'DAV Public School' },
    { rank: 12, recognition: 'Top 25', name: 'Yug Patel', school: 'Thakur Public School' },
    { rank: 13, recognition: 'Top 25', name: 'Sanskar Patel', school: 'AMNS International School' },
    { rank: 14, recognition: 'Top 25', name: 'Krishna S Kanth', school: 'Ponvidyashram Group of Senior Secondary Schools' },
    { rank: 15, recognition: 'Top 25', name: 'Prathiksha S.M.B', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 16, recognition: 'Top 25', name: 'D Tamanna', school: 'Pon Vidyashram Group of CBSE Schools' },
    { rank: 17, recognition: 'Top 25', name: 'Svara Sonkul', school: 'Bright Riders School' },
    { rank: 18, recognition: 'Top 25', name: 'Ishika Biju', school: 'Bright Riders School' },
    { rank: 19, recognition: 'Top 25', name: 'Kavya Marisetti', school: 'Army Public School - Rk Puram Neredmet' },
    { rank: 20, recognition: 'Top 25', name: 'Ojas A Kalmane', school: 'Navkis Educational Center, Gokula Campus' },
    { rank: 21, recognition: 'Top 25', name: 'Mia Khalid Al Khateeb', school: 'Rafic Hariri High School' },
    { rank: 22, recognition: 'Top 25', name: 'Chandrala Salagundi', school: 'Navkis Educational Centre, Bangalore' },
    { rank: 23, recognition: 'Top 25', name: 'Chaitanya Jaiswal', school: 'Thakur Public School' },
    { rank: 24, recognition: 'Top 25', name: 'Rithisha Jayaprakash', school: 'Bright Riders School' },
    { rank: 25, recognition: 'Top 25', name: 'Aditi Hingwasiya', school: 'Nalanda Public School' },
    { rank: 26, recognition: 'Top 50', name: 'Abilash Ceyon. S', school: 'Alphabet School' },
    { rank: 27, recognition: 'Top 50', name: 'Anay Somani', school: 'Thakur Public School' },
    { rank: 28, recognition: 'Top 50', name: 'Siddhi Patil', school: 'Bright Riders School' },
    { rank: 29, recognition: 'Top 50', name: 'Kora Aditya Tej Reddy', school: 'Suchitra Academy International School' },
    { rank: 30, recognition: 'Top 50', name: 'Dia Sobhrajani', school: 'St. Xavier\'s High School- Best CBSE School in Gurgaon' },
    { rank: 31, recognition: 'Top 50', name: 'Baikati Nihaanth Reddy', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 32, recognition: 'Top 50', name: 'Anap@1108', school: 'Bilinguale Grundschule Heidelberg | HPC Schulen' },
    { rank: 33, recognition: 'Top 50', name: 'Sharva Chilkar', school: 'Podar International School Besa Nagpur' },
    { rank: 34, recognition: 'Top 50', name: 'Kriya Shah', school: 'Sri Sri Ravishankar Vidya Mandir (SSRVM), Mulund, Mumbai' },
    { rank: 35, recognition: 'Top 50', name: 'Vaishnavi G. Kulkarni', school: 'Navkis Educational Centre, Bangalore' },
    { rank: 36, recognition: 'Top 50', name: 'Nadine Khairunisa Firdaus', school: 'Cambridge International School' },
    { rank: 37, recognition: 'Top 50', name: 'Lana Hassan Issa', school: 'Rafic Hariri High School' },
    { rank: 38, recognition: 'Top 50', name: 'Nookala Akshita', school: 'The Hyderabad Public School, Ramanthapur' },
    { rank: 39, recognition: 'Top 50', name: 'Koushani Paul', school: 'Global City International School' },
    { rank: 40, recognition: 'Top 50', name: 'Samanvii Botla', school: 'Suchitra Academy International School' },
    { rank: 41, recognition: 'Top 50', name: 'Akshita Singh', school: 'DAV Public School, Airoli' },
    { rank: 42, recognition: 'Top 50', name: 'Pranavi Kaushik', school: 'Bright Riders School' },
    { rank: 43, recognition: 'Top 50', name: 'Geet Raisinghani', school: 'Nalanda Public School' },
    { rank: 44, recognition: 'Top 50', name: 'Abilash Selvam', school: 'Bright Riders School' },
    { rank: 45, recognition: 'Top 50', name: 'Valerio Pérez', school: 'Gokkusagi Schools İzmir' },
    { rank: 46, recognition: 'Top 50', name: 'Suyaash Khandelia', school: 'Suchitra Academy International School' },
    { rank: 47, recognition: 'Top 50', name: 'Abdel Majid', school: 'Rafic Hariri High School' },
    { rank: 48, recognition: 'Top 50', name: 'Ibrahim Waseem Abou Zahr', school: 'Rafic Hariri High School' },
    { rank: 49, recognition: 'Top 50', name: 'Himonish', school: 'Shri Ram Centennial School' },
    { rank: 50, recognition: 'Top 50', name: 'Charan Tej Bandike', school: 'Reqelford International School' },
  ],
};
